# Generated by Django 2.0.6 on 2019-03-07 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '"activity"',
            },
        ),
        migrations.CreateModel(
            name='Deed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('deed_body', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '"deed"',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('be_operated', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': '"diary"',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=30)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': '"family"',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('permission_level', models.IntegerField()),
                ('father_id', models.CharField(blank=True, max_length=20, null=True)),
                ('children_id', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Family')),
            ],
            options={
                'db_table': '"person"',
            },
        ),
        migrations.AddField(
            model_name='diary',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Family'),
        ),
        migrations.AddField(
            model_name='diary',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Person'),
        ),
        migrations.AddField(
            model_name='deed',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Person'),
        ),
        migrations.AddField(
            model_name='activity',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Family'),
        ),
        migrations.AddField(
            model_name='activity',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Person'),
        ),
    ]
