# Generated by Django 2.0.6 on 2019-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='permission_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='deed',
            table='deed',
        ),
        migrations.AlterModelTable(
            name='diary',
            table='diary',
        ),
        migrations.AlterModelTable(
            name='family',
            table='family',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
