# Generated by Django 2.0.6 on 2019-03-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190307_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
