# Generated by Django 2.0.6 on 2019-03-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190309_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
