# Generated by Django 2.0.6 on 2019-03-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_person_nick_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='be_operated',
            new_name='diary',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='like_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
