# Generated by Django 2.0.6 on 2019-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20190314_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
